### ISSUE TITLE
可否增加一个dockerfile

### ISSUE THREAD

**Issue by Eloco** [jerryshell/my-flomo-web#1]
你好，可否增加Docker支持，方便部署

**Comment by jerryshell** [comment]
已经提上日程，啥时候有空我就加上😂

**Comment by jerryshell** [comment]
Dockerfile 已添加

**Comment by rebron1900** [comment]
大佬，如何指定api地址？尝试给容器设置环境变量，但是好像不起作用。

**Comment by jerryshell** [comment]
> 大佬，如何指定api地址？尝试给容器设置环境变量，但是好像不起作用。

看起来你好像已经知道怎么改了：https://github.com/rebron1900/my-flomo-web/commit/bd459ea9e2fd0d69e63bb76aa89095b42590124a

**Comment by rebron1900** [comment]
> > 大佬，如何指定api地址？尝试给容器设置环境变量，但是好像不起作用。
> 
> 看起来你好像已经知道怎么改了：[rebron1900@bd459ea](https://github.com/rebron1900/my-flomo-web/commit/bd459ea9e2fd0d69e63bb76aa89095b42590124a)

是的，只不过这个方式略微不是很方便，既然用docker来跑了，可以直接用环境变量来设置会方便一些。
